version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
      
  gateway:
    image: sltn011/gateway
    build: ./src/Gateway/
    ports:
      - "8080:8080"
      
  cars:
    image: sltn011/cars
    build: ./src/Cars/
    ports:
      - "8070:8070"
      
  rental:
    image: sltn011/rental
    build: ./src/Rental/
    ports:
      - "8060:8060"
      
  payment:
    image: sltn011/payment
    build: ./src/Payment/
    ports:
      - "8050:8050"
      
  accounts:
    image: sltn011/accounts
    build: ./src/Accounts/
    ports:
      - "8010:8010"
      
  stats:
    image: sltn011/stats
    build: ./src/Stats/
    ports:
      - "8100:8100"
      
  auth:
    image: sltn011/auth
    build: ./src/Auth/
    ports:
      - "9889:9889"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 5000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

volumes:
  db-data: