version: 13.8
port: 5432

default_database:
  name: postgres
  user: postgres
  password: postgres

users:
  - name: postgres
    password: postgres

datases:
  - name: rental
    user: program
  - name: payment
    user: program
  - name: cars
    user: program

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
