payment:
  service:
    port: 8050
    image:
      name: sltn011/payment
      version: "latest"
    database: 
      name: payments
rental:
  service:
    port: 8060
    image:
      name: sltn011/rental
      version: "latest"
    database: 
      name: rentals
cars:
  service:
    port: 8070
    image:
      name: sltn011/cars
      version: "latest"
    database: 
      name: cars
gateway:
  service:
    port: 8080
    image:
      name: sltn011/gateway
      version: "latest"
    isGateway: true
auth:
  service:
    port: 9889
    image:
      name: sltn011/auth
      version: "latest"
accounts:
  service:
    port: 8010
    image:
      name: sltn011/accounts
      version: "latest"
gateway:
  service:
    port: 8100
    image:
      name: sltn011/stats
      version: "latest"
